# Basic
title = "Cyril Vallée"
baseURL = "https://www.cyrilvallee.net/"
theme = "Vno Hugo"

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Livres"
    identifier = "livres"
    url = "https://cyrilvallee.com/"
    weight = 10

[taxonomies]
    tag = "tags"
    
[params]
author = "Cyril Vallée"
subtitle = "Romancier et auteur de l'imaginaire."
description = "Je publie des thrillers, des aventures fantastiques et de la SF."
welcomeMessage = "Je transforme la caféine en de bonnes histoires. Lisez mon dernier roman : Timeskippers - Livre I."

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "slate"

[params.comment]
disqus = ""
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
weibo = ""
github = ""
twitter = "_cyrilvallee_"
gplus = ""
mail = "salut@cyrilvallee.com"

[params.ga]
ID = ""
host = ""

# The blog button should not be removed.
[params.blogButton]
title = "Plus ?"
description = "En savoir plus sur Cyril Vallée"

[permalinks]
posts = "/:year/:month/:title/"
